package view;
/**
 * @author Wyldner
 *
 */
public class Principal {
	// ************ ESTOURAR HEAP ************
	public static void main(String[] args) {
		StringBuffer b = new StringBuffer();

		for (int i = 0; i < 2147483647; i++) {
			b.append("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut tellus elementum sagittis vitae. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. At ultrices mi tempus imperdiet nulla. Bibendum neque egestas congue quisque egestas diam in. Orci nulla pellentesque dignissim enim. Vitae ultricies leo integer malesuada nunc vel risus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Lorem mollis aliquam ut porttitor. Iaculis urna id volutpat lacus.\n"
					+ "\n"
					+ "Nibh mauris cursus mattis molestie a iaculis. Hendrerit gravida rutrum quisque non. Massa enim nec dui nunc mattis enim ut tellus elementum. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Ultrices tincidunt arcu non sodales neque. Facilisis magna etiam tempor orci eu lobortis elementum. Pellentesque massa placerat duis ultricies lacus sed turpis. Et malesuada fames ac turpis. Purus in mollis nunc sed id semper risus. Fermentum posuere urna nec tincidunt praesent semper feugiat. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Quis varius quam quisque id diam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Semper risus in hendrerit gravida rutrum quisque non.\n"
					+ "\n"
					+ "Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Rhoncus mattis rhoncus urna neque. Et ligula ullamcorper malesuada proin libero. Orci a scelerisque purus semper eget duis. Ut sem viverra aliquet eget sit. Lectus quam id leo in vitae turpis. Nulla aliquet enim tortor at auctor urna nunc. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Maecenas sed enim ut sem viverra aliquet. Ornare arcu dui vivamus arcu felis. Lacinia quis vel eros donec ac odio tempor orci dapibus. Arcu non sodales neque sodales ut etiam sit. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Sed felis eget velit aliquet. Semper feugiat nibh sed pulvinar proin gravida.\n"
					+ "\n"
					+ "In eu mi bibendum neque egestas congue quisque. Ut venenatis tellus in metus vulputate. Semper feugiat nibh sed pulvinar. At varius vel pharetra vel turpis nunc eget. Mi proin sed libero enim sed faucibus turpis. Arcu cursus euismod quis viverra nibh. Ornare massa eget egestas purus viverra accumsan in nisl. Aenean vel elit scelerisque mauris. Semper quis lectus nulla at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Amet consectetur adipiscing elit duis. Volutpat commodo sed egestas egestas. Massa ultricies mi quis hendrerit. Vel pretium lectus quam id leo in vitae turpis massa. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Et odio pellentesque diam volutpat commodo sed egestas egestas. Nam libero justo laoreet sit amet. Sit amet facilisis magna etiam tempor orci eu lobortis. Felis donec et odio pellentesque diam volutpat commodo sed. Ipsum a arcu cursus vitae congue mauris.\n"
					+ "\n"
					+ "Id porta nibh venenatis cras sed felis eget velit. Sed risus ultricies tristique nulla aliquet enim. Duis ut diam quam nulla porttitor. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Id faucibus nisl tincidunt eget nullam non nisi est sit. Massa ultricies mi quis hendrerit dolor magna. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Aliquam ultrices sagittis orci a scelerisque. Nulla facilisi nullam vehicula ipsum a arcu. Vel facilisis volutpat est velit egestas dui. Nam aliquam sem et tortor consequat. Dignissim convallis aenean et tortor. Aliquam ut porttitor leo a diam sollicitudin tempor id. Senectus et netus et malesuada fames ac turpis. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Eget dolor morbi non arcu risus. Ante metus dictum at tempor commodo ullamcorper. Sed tempus urna et pharetra pharetra massa massa. Mi quis hendrerit dolor magna eget est.\n"
					+ "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut tellus elementum sagittis vitae. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. At ultrices mi tempus imperdiet nulla. Bibendum neque egestas congue quisque egestas diam in. Orci nulla pellentesque dignissim enim. Vitae ultricies leo integer malesuada nunc vel risus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Lorem mollis aliquam ut porttitor. Iaculis urna id volutpat lacus.\n"
					+ "\n"
					+ "Nibh mauris cursus mattis molestie a iaculis. Hendrerit gravida rutrum quisque non. Massa enim nec dui nunc mattis enim ut tellus elementum. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Ultrices tincidunt arcu non sodales neque. Facilisis magna etiam tempor orci eu lobortis elementum. Pellentesque massa placerat duis ultricies lacus sed turpis. Et malesuada fames ac turpis. Purus in mollis nunc sed id semper risus. Fermentum posuere urna nec tincidunt praesent semper feugiat. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Quis varius quam quisque id diam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Semper risus in hendrerit gravida rutrum quisque non.\n"
					+ "\n"
					+ "Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Rhoncus mattis rhoncus urna neque. Et ligula ullamcorper malesuada proin libero. Orci a scelerisque purus semper eget duis. Ut sem viverra aliquet eget sit. Lectus quam id leo in vitae turpis. Nulla aliquet enim tortor at auctor urna nunc. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Maecenas sed enim ut sem viverra aliquet. Ornare arcu dui vivamus arcu felis. Lacinia quis vel eros donec ac odio tempor orci dapibus. Arcu non sodales neque sodales ut etiam sit. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Sed felis eget velit aliquet. Semper feugiat nibh sed pulvinar proin gravida.\n"
					+ "\n"
					+ "In eu mi bibendum neque egestas congue quisque. Ut venenatis tellus in metus vulputate. Semper feugiat nibh sed pulvinar. At varius vel pharetra vel turpis nunc eget. Mi proin sed libero enim sed faucibus turpis. Arcu cursus euismod quis viverra nibh. Ornare massa eget egestas purus viverra accumsan in nisl. Aenean vel elit scelerisque mauris. Semper quis lectus nulla at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Amet consectetur adipiscing elit duis. Volutpat commodo sed egestas egestas. Massa ultricies mi quis hendrerit. Vel pretium lectus quam id leo in vitae turpis massa. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Et odio pellentesque diam volutpat commodo sed egestas egestas. Nam libero justo laoreet sit amet. Sit amet facilisis magna etiam tempor orci eu lobortis. Felis donec et odio pellentesque diam volutpat commodo sed. Ipsum a arcu cursus vitae congue mauris.\n"
					+ "\n"
					+ "Id porta nibh venenatis cras sed felis eget velit. Sed risus ultricies tristique nulla aliquet enim. Duis ut diam quam nulla porttitor. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Id faucibus nisl tincidunt eget nullam non nisi est sit. Massa ultricies mi quis hendrerit dolor magna. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Aliquam ultrices sagittis orci a scelerisque. Nulla facilisi nullam vehicula ipsum a arcu. Vel facilisis volutpat est velit egestas dui. Nam aliquam sem et tortor consequat. Dignissim convallis aenean et tortor. Aliquam ut porttitor leo a diam sollicitudin tempor id. Senectus et netus et malesuada fames ac turpis. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Eget dolor morbi non arcu risus. Ante metus dictum at tempor commodo ullamcorper. Sed tempus urna et pharetra pharetra massa massa. Mi quis hendrerit dolor magna eget est.\n"
					+ "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut tellus elementum sagittis vitae. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. At ultrices mi tempus imperdiet nulla. Bibendum neque egestas congue quisque egestas diam in. Orci nulla pellentesque dignissim enim. Vitae ultricies leo integer malesuada nunc vel risus. Sagittis eu volutpat odio facilisis mauris sit amet massa. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Lorem mollis aliquam ut porttitor. Iaculis urna id volutpat lacus.\n"
					+ "\n"
					+ "Nibh mauris cursus mattis molestie a iaculis. Hendrerit gravida rutrum quisque non. Massa enim nec dui nunc mattis enim ut tellus elementum. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Ultrices tincidunt arcu non sodales neque. Facilisis magna etiam tempor orci eu lobortis elementum. Pellentesque massa placerat duis ultricies lacus sed turpis. Et malesuada fames ac turpis. Purus in mollis nunc sed id semper risus. Fermentum posuere urna nec tincidunt praesent semper feugiat. Pretium nibh ipsum consequat nisl vel pretium lectus quam. Quis varius quam quisque id diam. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Semper risus in hendrerit gravida rutrum quisque non.\n"
					+ "\n"
					+ "Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Rhoncus mattis rhoncus urna neque. Et ligula ullamcorper malesuada proin libero. Orci a scelerisque purus semper eget duis. Ut sem viverra aliquet eget sit. Lectus quam id leo in vitae turpis. Nulla aliquet enim tortor at auctor urna nunc. Donec adipiscing tristique risus nec feugiat in fermentum posuere. Maecenas sed enim ut sem viverra aliquet. Ornare arcu dui vivamus arcu felis. Lacinia quis vel eros donec ac odio tempor orci dapibus. Arcu non sodales neque sodales ut etiam sit. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Sed felis eget velit aliquet. Semper feugiat nibh sed pulvinar proin gravida.\n"
					+ "\n"
					+ "In eu mi bibendum neque egestas congue quisque. Ut venenatis tellus in metus vulputate. Semper feugiat nibh sed pulvinar. At varius vel pharetra vel turpis nunc eget. Mi proin sed libero enim sed faucibus turpis. Arcu cursus euismod quis viverra nibh. Ornare massa eget egestas purus viverra accumsan in nisl. Aenean vel elit scelerisque mauris. Semper quis lectus nulla at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Amet consectetur adipiscing elit duis. Volutpat commodo sed egestas egestas. Massa ultricies mi quis hendrerit. Vel pretium lectus quam id leo in vitae turpis massa. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Et odio pellentesque diam volutpat commodo sed egestas egestas. Nam libero justo laoreet sit amet. Sit amet facilisis magna etiam tempor orci eu lobortis. Felis donec et odio pellentesque diam volutpat commodo sed. Ipsum a arcu cursus vitae congue mauris.\n"
					+ "\n"
					+ "Id porta nibh venenatis cras sed felis eget velit. Sed risus ultricies tristique nulla aliquet enim. Duis ut diam quam nulla porttitor. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Id faucibus nisl tincidunt eget nullam non nisi est sit. Massa ultricies mi quis hendrerit dolor magna. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Aliquam ultrices sagittis orci a scelerisque. Nulla facilisi nullam vehicula ipsum a arcu. Vel facilisis volutpat est velit egestas dui. Nam aliquam sem et tortor consequat. Dignissim convallis aenean et tortor. Aliquam ut porttitor leo a diam sollicitudin tempor id. Senectus et netus et malesuada fames ac turpis. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Eget dolor morbi non arcu risus. Ante metus dictum at tempor commodo ullamcorper. Sed tempus urna et pharetra pharetra massa massa. Mi quis hendrerit dolor magna eget est.\n"
					+ "\n");
		}
	}
}
